fields:
    - name: url
      required: True
      viewby: True

    - name: title
      required: True

    - name: body
      required: True
      widget:
        type: TextArea()
        css_class: markitup

views:
- type: all
- type: all_count
